[project]
name = "ethbootstrap"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv.workspace]
members = [
    "packages/erc7744",
    "packages/util",
    "packages/deterministic-deployment-proxy",
]
