[project]
name = "deterministic-deployment-proxy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Julie B.", email = "no-reply@bbjubjub.fr" }
]
requires-python = ">=3.12"
dependencies = [
    "ethbootstrap-util",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
ethbootstrap-util = { workspace = true }
