[project]
name = "erc7744"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "deterministic-deployment-proxy",
    "solc-select>=1.1.0",
    "titanoboa>=0.2.7",
    "ethbootstrap-util",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
ethbootstrap-util = { workspace = true }
deterministic-deployment-proxy = { workspace = true }
