[project]
name = "ethbootstrap-seeds"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Julie B.", email = "no-reply@bbjubjub.fr" }
]
requires-python = ">=3.12"
dependencies = [
    "ethbootstrap-languages",
    "ethbootstrap-util",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "hypothesis>=6.135.26",
    "titanoboa>=0.2.7",
]

[tool.uv.sources]
ethbootstrap-languages = { workspace = true }
ethbootstrap-util = { workspace = true }
